development:
  adapter: oracle_enhanced
  database: XE
  username: summer
  password: summer

test:
  adapter: oracle_enhanced
  database: XE
  username: summer
  password: summer

production:
  adapter: oracle_enhanced
  database: XE
  username: summer
  password: summer